ServerEvents.recipes(event =>{
    // Enrichment 
    event.recipes.gtceu.mixer("enrichment/prudentium")
        .itemInputs("2x gtceu:inferium_dust", "8x mysticalagriculture:air_essence", "8x mysticalagriculture:fire_essence", "8x mysticalagriculture:earth_essence", "8x mysticalagriculture:water_essence")
        .itemOutputs("gtceu:prudentium_dust")
        .duration(200)
        .EUt(30)
    event.recipes.gtceu.mixer("enrichment/tertium")
        .itemInputs("2x gtceu:prudentium_dust", "8x mysticalagriculture:air_essence", "8x mysticalagriculture:fire_essence", "8x mysticalagriculture:earth_essence", "8x mysticalagriculture:water_essence")
        .itemOutputs("gtceu:tertium_dust")
        .duration(200)
        .EUt(120)
    event.recipes.gtceu.mixer("enrichment/imperium")
        .itemInputs("2x gtceu:tertium_dust", "8x mysticalagriculture:air_essence", "8x mysticalagriculture:fire_essence", "8x mysticalagriculture:earth_essence", "8x mysticalagriculture:water_essence")
        .itemOutputs("gtceu:imperium_dust")
        .duration(200)
        .EUt(480)
    event.recipes.gtceu.mixer("enrichment/supremium")
        .itemInputs("32x gtceu:inferium_dust", "8x mysticalagriculture:air_essence", "8x mysticalagriculture:fire_essence", "8x mysticalagriculture:earth_essence", "8x mysticalagriculture:water_essence")
        .itemOutputs("gtceu:supremium_dust")
        .duration(200)
        .EUt(1920)
    event.recipes.gtceu.mixer("enrichment/insanium")
        .itemInputs("2x gtceu:supremium_dust", "8x mysticalagriculture:air_essence", "8x mysticalagriculture:fire_essence", "8x mysticalagriculture:earth_essence", "8x mysticalagriculture:water_essence")
        .itemOutputs("gtceu:insanium_dust")
        .duration(200)
        .EUt(7680)
    // Rich recipes
    event.recipes.gtceu.agricultural_fabrication("enrichment/prudentium")
        .itemInputs("gtceu:inferium_dust", "16x gtceu:air_elementia_gem", "16x gtceu:fire_elementia_gem", "16x gtceu:earth_elementia_gem", "16x gtceu:water_elementia_gem")
        .itemOutputs("gtceu:prudentium_dust")
        .duration(200)
        .EUt(120)
    event.recipes.gtceu.agricultural_fabrication("enrichment/tertium")
        .itemInputs("gtceu:prudentium_dust", "16x gtceu:air_elementia_gem", "16x gtceu:fire_elementia_gem", "16x gtceu:earth_elementia_gem", "16x gtceu:water_elementia_gem")
        .itemOutputs("gtceu:tertium_dust")
        .duration(200)
        .EUt(480)
    event.recipes.gtceu.agricultural_fabrication("enrichment/imperium")
        .itemInputs("gtceu:tertium_dust", "16x gtceu:air_elementia_gem", "16x gtceu:fire_elementia_gem", "16x gtceu:earth_elementia_gem", "16x gtceu:water_elementia_gem")
        .itemOutputs("gtceu:imperium_dust")
        .duration(200)
        .EUt(1920)
    event.recipes.gtceu.agricultural_fabrication("enrichment/supremium")
        .itemInputs("16x gtceu:inferium_dust", "16x gtceu:air_elementia_gem", "16x gtceu:fire_elementia_gem", "16x gtceu:earth_elementia_gem", "16x gtceu:water_elementia_gem")
        .itemOutputs("gtceu:supremium_dust")
        .duration(200)
        .EUt(7680)
    event.recipes.gtceu.agricultural_fabrication("enrichment/insanium")
        .itemInputs("gtceu:supremium_dust", "16x gtceu:air_elementia_gem", "16x gtceu:fire_elementia_gem", "16x gtceu:earth_elementia_gem", "16x gtceu:water_elementia_gem")
        .itemOutputs("gtceu:insanium_dust")
        .duration(200)
        .EUt(30720)

    
    // Gemstone crafting
    const dusts = [
        "inferium",
        //"prudentium", "tertium", "imperium", 
        "supremium", 
        "awakened_supremium"
    ]

    dusts.forEach(tier =>{
        event.recipes.gtceu.alloy_smelter(`gemstone/${tier}`)
            .itemInputs(`2x #forge:ingots/${tier}`, "mysticalagriculture:prosperity_gemstone")
            .itemOutputs(`mysticalagriculture:${tier}_gemstone`)
            .duration(310)
            .EUt(7)
        })

    // EBF
    event.recipes.gtceu.electric_blast_furnace("kubejs:prudentium_ingot")
        .itemInputs("gtceu:prudentium_dust", "gtceu:prosperity_ingot")
        .itemOutputs("gtceu:prudentium_ingot", "gtceu:small_elemental_sludge_dust")
        .blastFurnaceTemp(1700)
        .duration(570)
        .EUt(120)
    event.recipes.gtceu.electric_blast_furnace("kubejs:tertium_ingot")
        .itemInputs("gtceu:tertium_dust", "gtceu:prosperity_ingot")
        .itemOutputs("gtceu:tertium_ingot", "gtceu:elemental_sludge_dust")
        .blastFurnaceTemp(1700)
        .duration(740)
        .EUt(480)
    event.recipes.gtceu.electric_blast_furnace("kubejs:imperium_ingot")
        .itemInputs("gtceu:imperium_dust", "gtceu:prosperity_ingot")
        .itemOutputs("gtceu:imperium_ingot", "gtceu:elemental_sludge_dust")
        .blastFurnaceTemp(1847)
        .duration(912)
        .EUt(1920)
    event.recipes.gtceu.electric_blast_furnace("kubejs:supremium_ingot")
        .itemInputs("gtceu:supremium_dust", "gtceu:prosperity_ingot")
        .itemOutputs("gtceu:supremium_ingot", "gtceu:elemental_sludge_dust")
        .blastFurnaceTemp(2987)
        .duration(630)
        .EUt(7680)
    event.recipes.gtceu.electric_blast_furnace("kubejs:insanium_ingot")
        .itemInputs("gtceu:insanium_dust", "gtceu:prosperity_ingot")
        .itemOutputs("gtceu:insanium_ingot", "gtceu:elemental_sludge_dust")
        .blastFurnaceTemp(4500)
        .duration(745)
        .EUt(30720)
    
    // Awk. Supremium
    event.recipes.gtceu.fusion_reactor("kubejs:awakened_supremium_ingot")
        .inputFluids("gtceu:insanium 16", "gtceu:supremium 16")
        .outputFluids("gtceu:awakened_supremium 16")
        .duration(64)
        .fusionStartEU(180000000)
        .EUt(GTValues.VH[GTValues.LuV])


})