ServerEvents.recipes(event=>{
    
    // Dust block from sand
    event.recipes.gtceu.forge_hammer("dust_block_from_sand_block")
        .itemInputs("#minecraft:smelts_to_glass")
        .itemOutputs("kubejs:dust")
        .duration(10)
        .EUt(16)
    // Dust to clay
    event.recipes.gtceu.chemical_reactor("clay_from_dust_block")
        .itemInputs("kubejs:dust")
        .inputFluids("minecraft:water 1000")
        .itemOutputs("minecraft:clay")
        .duration(200)
        .EUt(24)
    // Clay to clay ball
    event.shapeless("4x minecraft:clay_ball", ["minecraft:clay"])

    // Chipped tinker's table
    event.replaceInput({ id: "chipped:benches/mechanist_workbench" }, "minecraft:tnt", "#forge:chests")

    // Sunflower to seed oil
    event.remove({id:'gtceu:extractor/sunflower_dye'})
    event.recipes.gtceu.extractor("sunflower_to_seed_oil")
        .itemInputs("minecraft:sunflower")
        .outputFluids("gtceu:seed_oil 20")
        .duration(32)
        .EUt(2)

    // Lava from Magma
    event.recipes.gtceu.chemical_reactor("lava_from_magma")
        .itemInputs("minecraft:magma_block")
        .outputFluids(Fluid.of("minecraft:lava", 1000))
        .duration(120)
        .EUt(16)

    // Slime ball from plant ball
    event.smelting("2x minecraft:slime_ball", "gtceu:plant_ball")

    // Let Oilsands have multiple types of oil
    event.remove({id:"gtceu:centrifuge/oilsands_dust_separation"})
    event.recipes.gtceu.centrifuge("oilsands_to_oil")
        .itemInputs("gtceu:oilsands_dust")
        .chancedOutput("minecraft:sand", 5000, 5000)
        .outputFluids("gtceu:oil 1000")
        .duration(200)
        .EUt(30)
        .circuit(3)
    event.recipes.gtceu.centrifuge("oilsands_to_light_oil")
        .itemInputs("gtceu:oilsands_dust")
        .chancedOutput("minecraft:sand", 5000, 5000)
        .outputFluids("gtceu:oil_light 500")
        .duration(200)
        .EUt(30)
        .circuit(4)
    event.recipes.gtceu.centrifuge("oilsands_to_heavy_oil")
        .itemInputs("gtceu:oilsands_dust")
        .chancedOutput("minecraft:sand", 5000, 5000)
        .outputFluids("gtceu:oil_heavy 2000")
        .duration(200)
        .EUt(30)
        .circuit(2)
    event.recipes.gtceu.centrifuge("oilsands_to_raw_oil")
        .itemInputs("gtceu:oilsands_dust")
        .chancedOutput("minecraft:sand", 5000, 5000)
        .outputFluids("gtceu:oil_medium 1000")
        .duration(200)
        .EUt(30)
        .circuit(1)

    // Sodium to Sodium Hydroxide
    event.recipes.gtceu.chemical_reactor("na_to_naoh")
        .itemInputs("gtceu:sodium_dust")
        .inputFluids("minecraft:water 1000")
        .itemOutputs("3x gtceu:sodium_hydroxide_dust")
        .outputFluids("gtceu:hydrogen 1000")
        .duration(50)
        .EUt(100)

    // Beetroot to seeds
    event.recipes.gtceu.macerator("beetroot_seeds_from_beetroot")
        .itemInputs("minecraft:beetroot")
        .itemOutputs("minecraft:beetroot_seeds")
        .duration(200)
        .EUt(2)
    // Wheat to flour + seeds
    event.remove({id: 'gtceu:macerator/macerate_wheat'})
    event.recipes.gtceu.macerator("macerate_wheat")
        .itemInputs("minecraft:wheat")
        .itemOutputs("minecraft:wheat_seeds")
        .duration(98)
        .EUt(2)
    event.recipes.gtceu.forge_hammer("wheat_to_flour")
        .itemInputs("minecraft:wheat")
        .itemOutputs("gtceu:wheat_dust")
        .duration(48)
        .EUt(2)

    // Drill recipes for data simulation
    event.recipes.gtceu.assembler("diamond_drill")
        .itemInputs("3x #forge:plates/diamond", "2x #forge:plates/steel", "#forge:ingots/steel")
        .inputFluids("gtceu:soldering_alloy 72")
        .itemOutputs("gtceu:diamond_drill_head")
        .duration(120)
        .EUt(16)

    // Fix ilmenite -> rutile stoich
    event.remove({id:"gtceu:electric_blast_furnace/rutile_from_ilmenite"})
    event.recipes.gtceu.electric_blast_furnace("rutile_from_ilmenite")
        .itemInputs("10x gtceu:ilmenite_dust", "2x gtceu:carbon_dust")
        .itemOutputs("2x gtceu:wrought_iron_ingot", "6x gtceu:rutile_dust")
        .outputFluids("gtceu:carbon_dioxide 2000")
        .duration(1600)
        .blastFurnaceTemp(1700)
        .EUt(480)

    // XP canning and uncanning
    event.recipes.gtceu.canner("xp_unbottling")
        .itemInputs("minecraft:experience_bottle")
        .itemOutputs("minecraft:glass_bottle")
        .outputFluids("enderio:xp_juice 250")
        .duration(400)
        .EUt(2)
    event.recipes.gtceu.canner("xp_bottling")
        .itemInputs("minecraft:glass_bottle")
        .inputFluids("enderio:xp_juice 250")
        .itemOutputs("minecraft:experience_bottle")
        .duration(400)
        .EUt(2)

    // Instruction Set Machine
    event.recipes.gtceu.assembler("kubejs:instruction_set_machine")
        .itemInputs("4x #forge:double_plates/steel", "gtceu:computer_monitor_cover", "3x #gtceu:circuits/mv", "2x gtceu:silicon_wafer", "8x #gtceu:transistors", "32x #forge:fine_wires/electrum")
        .itemOutputs("kubejs:instruction_set_machine")
        .duration(400)
        .EUt(GTValues.VA[GTValues.HV])

    // Atmospheric Samples
    event.recipes.gtceu.scanner("kubejs:overworld_sample_from_drum")
        .itemInputs(Item.of('gtceu:steel_drum', '{Fluid:{Amount:64000,FluidName:"gtceu:air"}}').strongNBT())
        .notConsumable("kubejs:instruction_set_machine")
        .itemOutputs("kubejs:overworld_atmospheric_sample")
        .duration(4800)
        .EUt(16)

    event.recipes.gtceu.scanner("kubejs:nether_sample_from_drum")
        .itemInputs(Item.of('gtceu:aluminium_drum', '{Fluid:{Amount:128000,FluidName:"gtceu:nether_air"}}').strongNBT())
        .notConsumable("kubejs:instruction_set_machine")
        .itemOutputs("kubejs:nether_atmospheric_sample")
        .duration(7200)
        .EUt(16)

    event.recipes.gtceu.scanner("kubejs:end_sample_from_drum")
        .itemInputs(Item.of('gtceu:stainless_steel_drum', '{Fluid:{Amount:256000,FluidName:"gtceu:ender_air"}}').strongNBT())
        .notConsumable("kubejs:instruction_set_machine")
        .itemOutputs("kubejs:end_atmospheric_sample")
        .duration(9600)
        .EUt(16)

    //Atmoseeds
    event.recipes.gtceu.centrifuge("kubejs:overworld_atmoseeds_from_sample")
        .notConsumable("kubejs:overworld_atmospheric_sample")
        .itemInputs("24x gtceu:bio_chaff")
        .inputFluids("gtceu:liquid_air 24000")
        .chancedOutput("kubejs:hydrogen_atmoseeds", 5000, 1200)
        .chancedOutput("kubejs:nitrogen_atmoseeds", 3200, 1000)
        .chancedOutput("kubejs:argon_atmoseeds", 1200, 800)
        .duration(800)
        .EUt(GTValues.VHA[GTValues.HV])

    event.recipes.gtceu.centrifuge("kubejs:nether_atmoseeds_from_sample")
        .notConsumable("kubejs:nether_atmospheric_sample")
        .itemInputs("48x gtceu:bio_chaff")
        .inputFluids("gtceu:liquid_nether_air 32000")
        .chancedOutput("kubejs:sulfur_atmoseeds", 5000, 1200)
        .chancedOutput("kubejs:helium_atmoseeds", 3200, 1000)
        .chancedOutput("kubejs:neon_atmoseeds", 1200, 800)
        .duration(800)
        .EUt(GTValues.VHA[GTValues.EV])

    event.recipes.gtceu.centrifuge("kubejs:ender_atmoseeds_from_sample")
        .notConsumable("kubejs:end_atmospheric_sample")
        .itemInputs("64x gtceu:bio_chaff")
        .inputFluids("gtceu:liquid_ender_air 48000")
        .chancedOutput("kubejs:deuterium_atmoseeds", 5000, 1200)
        .chancedOutput("kubejs:tritium_atmoseeds", 2400, 1000)
        .chancedOutput("kubejs:xenon_atmoseeds", 1000, 800)
        .chancedOutput("kubejs:krypton_atmoseeds", 1000, 800)
        .chancedOutput("kubejs:radon_atmoseeds", 1000, 800)
        .duration(800)
        .EUt(GTValues.VHA[GTValues.IV])
    
})