/**
 * Multiblock registry
 * use below for reference if necessary for multiblock creation
 * avoid other scripts other than this for multiblock creation
 * if not broken, avoid touching
 */

const LargeTurbineMachine = Java.loadClass("com.gregtechceu.gtceu.common.machine.multiblock.generator.LargeTurbineMachine")
const FusionReactorMachine = Java.loadClass("com.gregtechceu.gtceu.common.machine.multiblock.electric.FusionReactorMachine")
const WorkableElectricMultiblockMachine = Java.loadClass("com.gregtechceu.gtceu.api.machine.multiblock.WorkableElectricMultiblockMachine")


GTCEuStartupEvents.registry('gtceu:recipe_type', event=>{

    // GTCEu RM

    
    // Mystical Agriculture
    event.create('synthetic_fluid')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(2, 0, 1, 6)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.CHEMICAL)

    event.create('synthetic_solid')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(2, 6, 1, 0)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.CHEMICAL)

    event.create('synthetic_lifeform')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(2, 6, 1, 1)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COMPUTATION)

    event.create('greenhouse')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(3, 6, 1, 2)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_RECYCLER, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.BATH)

    event.create('elemental_generator')
        .category('multiblock')
        .setEUIO('out')
        .setMaxIOSize(0, 0, 1, 1)
        .setSlotOverlay(false, false, GuiTextures.TURBINE_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.TURBINE)

    event.create('crystal_matrix')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(1, 1, 1, 1)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_CRYSTALLIZATION, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.CENTRIFUGE)

    event.create('draconitium_energy')
        .category('multiblock')
        .setEUIO('out')
        .setMaxIOSize(0, 0, 2, 1)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_FUSION, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.JET_ENGINE)
})

GTCEuStartupEvents.registry('gtceu:machine', event=>{

    // Mystical Agriculture
    // Synthetic Fluid Rig
    event.create('synthetic_fluid_rig', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes('synthetic_fluid')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("AAA", "#F#", "#F#", "#F#", "###", "###", "###")
            .aisle("AAA", "FSF", "FSF", "FSF", "#F#", "#F#", "#F#")
            .aisle("A@A", "#F#", "#F#", "#F#", "###", "###", "###")
            .where('@', Predicates.controller(Predicates.blocks(definition.get())))
            .where('A', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get()).setMinGlobalLimited(3)
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1)))
            .where('S', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get()))
            .where('F', Predicates.blocks("gtceu:steel_frame"))
            .where(" ", Predicates.air())
            .where("#", Predicates.any())
            .build())
        .workableCasingRenderer("gtceu:block/casings/solid/machine_casing_solid_steel", "gtceu:block/multiblock/large_chemical_reactor", false)

    // Synthetic Solid Rig
    event.create('synthetic_solid_rig', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes('synthetic_solid')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('BBB', '#F#', "#F#", "#F#", "###", "###", "###")
            .aisle("BBB", "FSF", "FSF", "FSF", "#F#", "#F#", "#F#")
            .aisle("B$B", "#F#", "#F#", "#F#", "###", "###", "###")
            .where('$', Predicates.controller(Predicates.blocks(definition.get())))
            .where('B', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get()).setMinGlobalLimited(3)
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1)))
            .where('S', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get()))
            .where('F', Predicates.blocks("gtceu:steel_frame"))
            .where(" ", Predicates.air())
            .where("#", Predicates.any())
            .build())
        .workableCasingRenderer("gtceu:block/casings/solid/machine_casing_solid_steel", "gtceu:block/multiblock/large_miner", false)

    // Synthetic Lifeform Simulator
    event.create('synthetic_lifeform_simulator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes('synthetic_lifeform')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCC', 'CCC', 'CCC')
            .aisle('CCC', 'C C', 'CCC')
            .aisle('CCC', 'C%C', 'CCC')
            .where('%', Predicates.controller(Predicates.blocks(definition.get())))
            .where('C', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get()).setMinGlobalLimited(6)
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1)))
            .where(" ", Predicates.air())
            .build())
        .workableCasingRenderer("gtceu:block/casings/solid/machine_casing_solid_steel", "gtceu:block/multiblock/network_switch", false)

    // 5x5x5 Greenhouse
    event.create('greenhouse', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes(['greenhouse', 'seed_growth'])
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('DDDDD', 'DDDDD', 'GGGGG', 'GGGGG', '#GGG#')
            .aisle('DDDDD', 'DFFFD', 'I   I', 'I   I', '#III#')
            .aisle('DDDDD', 'DFFFD', 'I   I', 'I   I', '#III#')
            .aisle('DDDDD', 'DFFFD', 'I   I', 'I   I', '#III#')
            .aisle('DDDDD', 'DFFFD', 'I   I', 'I   I', '#III#')
            .aisle('DDDDD', 'DFFFD', 'I   I', 'I   I', '#III#')
            .aisle('DDDDD', 'DD&DD', 'GGGGG', 'GGGGG', '#GGG#')
            .where('&', Predicates.controller(Predicates.blocks(definition.get())))
            .where('F', Predicates.blocks("farmersdelight:rich_soil"))
            .where('D', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get())
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1)))
            .where('G', Predicates.blocks(GTBlocks.CASING_TEMPERED_GLASS.get())
                .or(Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get())))
            .where('I', Predicates.blocks(GTBlocks.CASING_TEMPERED_GLASS.get()))
            .where('#', Predicates.any())
            .where(' ', Predicates.air())
            .build())
        .workableCasingRenderer("gtceu:block/casings/solid/machine_casing_solid_steel", "gtceu:block/multiblock/greenhouse", false)
 
    // It works!
    event.create('elemental_turbine', 'multiblock')
        .machine((holder) => new LargeTurbineMachine(holder, GTValues.EV))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes('elemental_generator')
        .recipeModifiers([MachineModifiers.LARGE_TURBINE])
        .appearanceBlock(() => Block.getBlock("kubejs:supremium_casing"))
        .generator(true)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('AAAA', 'ABBA', 'AAAA')
            .aisle('ABBA', 'CEED', 'ABBA')
            .aisle('AAAA', 'A@AA', 'AAAA')
            .where('@', Predicates.controller(Predicates.blocks(definition.get())))
            .where('A', Predicates.blocks("kubejs:supremium_casing"))
            .where('B', Predicates.abilities(PartAbility.IMPORT_FLUIDS)
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.blocks("kubejs:supremium_casing")))
            .where('C', Predicates.abilities(PartAbility.ROTOR_HOLDER))
            .where('D', Predicates.abilities(PartAbility.OUTPUT_ENERGY))
            .where('E', Predicates.blocks(GTBlocks.CASING_STAINLESS_STEEL_GEARBOX.get()))
            .where(' ', Predicates.air())
            .build())
        .workableCasingRenderer("kubejs:block/supremium/supremium_casing", "gtceu:block/multiblock/distillation_tower", false)

    event.create('critical_point_crystal_matrix', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes('crystal_matrix')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .appearanceBlock(() => Block.getBlock("kubejs:supremium_casing"))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('XXXCCCCCXXX', 'XXXCCCCCXXX', 'XXXDXXXDXXX', 'XXXDXXXDXXX', 'XXXDXXXDXXX', 'XXXXXXXXXXX', 'XXXXXXXXXXX', 'XXXXXXXXXXX', 'XXXDXXXDXXX', 'XXXDXXXDXXX', 'XXXDXXXDXXX', 'XXXCCCCCXXX', 'XXXCCCCCXXX')
            .aisle('XXCCCCCCCXX', 'XXCCCCCCCXX', 'XXXXCCCXXXX', 'XXXXBBBXXXX', 'XXXDAAADXXX', 'XXXDDDDDXXX', 'XXXXDXDXXXX', 'XXXDDDDDXXX', 'XXXDAAADXXX', 'XXXXBBBXXXX', 'XXXXCCCXXXX', 'XXCCCCCCCXX', 'XXCCCCCCCXX')
            .aisle('XCCCCCCCCCX', 'XCCCCCCCCCX', 'XXXXCCCXXXX', 'XXXXBEBXXXX', 'XXXXACAXXXX', 'XXDXXXXXDXX', 'XXXXXXXXXXX', 'XXDXXXXXDXX', 'XXXXAAAXXXX', 'XXXXBEBXXXX', 'XXXXCCCXXXX', 'XCCCCCCCCCX', 'XCCCCCCCCCX')
            .aisle('CCCCCCCCCCC', 'CCCCCCCCCCC', 'DXXXCCCXXXD', 'DXXXBEBXXXD', 'DDXXAAAXXDD', 'XDXXXXXXXDX', 'XXXXXXXXXXX', 'XDXXXXXXXDX', 'DDXXAAAXXDD', 'DXXXBEBXXXD', 'DXXXCCCXXXD', 'CCCCCCCCCCC', 'CCCCCCCCCCC')
            .aisle('CCCCCCCCCCC', 'CCCCCCCCCCC', 'XCCCCCCCCCX', 'XBBBAEABBBX', 'XAAAAAAAAAX', 'XDXXABAXXDX', 'XDXXABAXXDX', 'XDXXABAXXDX', 'XAAAAAAAAAX', 'XBBBAEABBBX', 'XCCCCCCCCCX', 'CCCCCCCCCCC', 'CCCCCCCCCCC')
            .aisle('CCCCCCCCCCC', 'CCCCCCCCCCC', 'XCCCCCCCCCX', 'XBEEE EEEBX', 'XACAA AACAX', 'XDXXB BXXDX', 'XXXXB BXXXX', 'XDXXB BXXDX', 'XAAAA AAAAX', 'XBEEE EEEBX', 'XCCCCCCCCCX', 'CCCCCCCCCCC', 'CCCCCCCCCCC')
            .aisle('CCCCCCCCCCC', 'CCCCCCCCCCC', 'XCCCCCCCCCX', 'XBBBAEABBBX', 'XAAAAAAAAAX', 'XDXXABAXXDX', 'XDXXABAXXDX', 'XDXXABAXXDX', 'XAAAAAAAAAX', 'XBBBAEABBBX', 'XCCCCCCCCCX', 'CCCCCCCCCCC', 'CCCCCCCCCCC')
            .aisle('CCCCCCCCCCC', 'CCCCCCCCCCC', 'DXXXCCCXXXD', 'DXXXBEBXXXD', 'DDXXAAAXXDD', 'XDXXXXXXXDX', 'XXXXXXXXXXX', 'XDXXXXXXXDX', 'DDXXAAAXXDD', 'DXXXBEBXXXD', 'DXXXCCCXXXD', 'CCCCCCCCCCC', 'CCCCCCCCCCC')
            .aisle('XCCCCCCCCCX', 'XCCCCCCCCCX', 'XXXXCCCXXXX', 'XXXXBEBXXXX', 'XXXXACAXXXX', 'XXDXXXXXDXX', 'XXXXXXXXXXX', 'XXDXXXXXDXX', 'XXXXAAAXXXX', 'XXXXBEBXXXX', 'XXXXCCCXXXX', 'XCCCCCCCCCX', 'XCCCCCCCCCX')
            .aisle('XXCCCCCCCXX', 'XXCCCCCCCXX', 'XXXXCCCXXXX', 'XXXXBBBXXXX', 'XXXDAAADXXX', 'XXXDDDDDXXX', 'XXXXDXDXXXX', 'XXXDDDDDXXX', 'XXXDAAADXXX', 'XXXXBBBXXXX', 'XXXXCCCXXXX', 'XXCCCCCCCXX', 'XXCCCCCCCXX')
            .aisle('XXXCCCCCXXX', 'XXXCC@CCXXX', 'XXXDXXXDXXX', 'XXXDXXXDXXX', 'XXXDXXXDXXX', 'XXXXXXXXXXX', 'XXXXXXXXXXX', 'XXXXXXXXXXX', 'XXXDXXXDXXX', 'XXXDXXXDXXX', 'XXXDXXXDXXX', 'XXXCCCCCXXX', 'XXXCCCCCXXX')
            .where('@', Predicates.controller(Predicates.blocks(definition.get())))
            .where('A', Predicates.blocks("kubejs:supremium_casing"))
            .where('B', Predicates.blocks(GTBlocks.CASING_LAMINATED_GLASS.get()))
            .where('C', Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(2)
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(2))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(4))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.blocks("kubejs:supremium_casing")))
            .where('D', Predicates.blocks("gtceu:prosperity_frame"))
            .where('E', Predicates.blocks("gtceu:air_elementia_block").setExactLimit(6)
                .or(Predicates.blocks("gtceu:fire_elementia_block").setExactLimit(6))
                .or(Predicates.blocks("gtceu:earth_elementia_block").setExactLimit(6))
                .or(Predicates.blocks("gtceu:water_elementia_block").setExactLimit(6)))
            .where(' ', Predicates.air())
            .where('X', Predicates.any())
            .build())
        .workableCasingRenderer("kubejs:block/supremium/supremium_casing", "gtceu:block/multiblock/gcym/large_autoclave", false)

    event.create('draconitium_collider', 'multiblock')
        .machine((holder) => new FusionReactorMachine(holder, GTValues.ZPM))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes('draconitium_energy')
        .appearanceBlock(() =>Block.getBlock("kubejs:draconitium_fusion_casing"))
        .recipeModifiers([MachineModifiers.FUSION_REACTOR])
        .generator(true)
        
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('XXXXXXXXXXXXXXX', 'XXXXXXDEDXXXXXX', 'XXXXXXXXXXXXXXX')
            .aisle('XXXXXXDADXXXXXX', 'XXXXEE   EEXXXX', 'XXXXXXDADXXXXXX')
            .aisle('XXXXAAXXXAAXXXX', 'XXXC  AEA  CXXX', 'XXXXAAXXXAAXXXX')
            .aisle('XXXAXXXXXXXAXXX', 'XXCBCEXXXECBCXX', 'XXXAXXXXXXXAXXX')
            .aisle('XXAXXXXXXXXXAXX', 'XE CXXXXXXXC EX', 'XXAXXXXXXXXXAXX')
            .aisle('XXAXXXXXXXXXAXX', 'XE EXXXXXXXE EX', 'XXAXXXXXXXXXAXX')
            .aisle('XDXXXXXXXXXXXDX', 'D AXXXXXXXXXA D', 'XDXXXXXXXXXXXDX')
            .aisle('XAXXXXXXXXXXXAX', 'E EXXXXXXXXXA E', 'XAXXXXXXXXXXXAX')
            .aisle('XDXXXXXXXXXXXDX', 'D AXXXXXXXXXA D', 'XDXXXXXXXXXXXDX')
            .aisle('XXAXXXXXXXXXAXX', 'XE EXXXXXXXE EX', 'XXAXXXXXXXXXAXX')
            .aisle('XXAXXXXXXXXXAXX', 'XE CXXXXXXXC EX', 'XXAXXXXXXXXXAXX')
            .aisle('XXXAXXXXXXXAXXX', 'XXCBCEXXXECBCXX', 'XXXAXXXXXXXAXXX')
            .aisle('XXXXAAXXXAAXXXX', 'XXXC  AAA  CXXX', 'XXXXAAXXXAAXXXX')
            .aisle('XXXXXXDADXXXXXX', 'XXXXEE   EEXXXX', 'XXXXXXDADXXXXXX')
            .aisle('XXXXXXXXXXXXXXX', 'XXXXXXA@AXXXXXX', 'XXXXXXXXXXXXXXX')
            .where('@', Predicates.controller(Predicates.blocks(definition.get())))
            .where('A', Predicates.blocks("kubejs:draconitium_fusion_casing"))
            .where('B', Predicates.blocks(GTBlocks.SUPERCONDUCTING_COIL.get()))
            .where('C', Predicates.abilities(PartAbility.OUTPUT_ENERGY)
                .setMinGlobalLimited(2)
                .setMaxGlobalLimited(8)
                .or(Predicates.blocks("kubejs:draconitium_fusion_casing"))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY)
                    .setMaxGlobalLimited(8)))
            .where('D', Predicates.abilities(PartAbility.IMPORT_FLUIDS)
                .setMinGlobalLimited(4)
                .setMaxGlobalLimited(8)
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS)
                    .setMinGlobalLimited(4)
                    .setMinGlobalLimited(8))
                .or(Predicates.blocks("kubejs:draconitium_fusion_casing")))
            .where('E', Predicates.blocks(GTBlocks.FUSION_GLASS.get()))
            //.where('F', Predicates.blocks('kubejs:draconitium_casing'))
            .where('X', Predicates.any())
            .where(' ', Predicates.air())
            .build())
        .workableCasingRenderer("kubejs:block/fusion/draconitium_fusion_casing", "gtceu:block/multiblock/fusion_reactor", false)
})