ServerEvents.recipes(event=>{

    event.remove({id:/enderio:copper_alloy.*/})
    event.replaceInput({mod: 'enderio'}, 'enderio:copper_alloy_ingot', 'gtceu:electrical_steel_ingot')
    event.replaceInput({mod: 'enderio'}, 'enderio:redstone_alloy_ingot', 'gtceu:red_alloy_ingot')
    event.replaceInput({mod: 'enderio'}, 'enderio:copper_alloy_ingot', 'gtceu:electrical_steel_ingot')
    
    // Electrical Steel
    event.remove({id:'enderio:grindingball/copper_alloy_grinding_ball'})
    event.remove({id:'enderio:alloy_smelting/copper_alloy_ingot'})
    event.recipes.gtceu.alloy_smelter('electrical_steel_from_dust')
        .itemInputs('#forge:dusts/steel', 'gtceu:silicon_dust')
        .itemOutputs('2x gtceu:electrical_steel_ingot')
        .duration(140)
        .EUt(7)
    event.recipes.gtceu.alloy_smelter('electrical_steel_from_ingot')
        .itemInputs('#forge:ingots/steel', 'gtceu:silicon_dust')
        .itemOutputs('2x gtceu:electrical_steel_ingot')
        .duration(140)
        .EUt(7)
    // Pulsating Alloy
    event.remove({id:'enderio:alloy_smelting/pulsating_alloy_ingot'})
    event.recipes.gtceu.alloy_smelter('pulsating_alloy_from_dust')
        .itemInputs('#forge:dusts/iron', 'minecraft:ender_pearl')
        .itemOutputs('gtceu:pulsating_alloy_ingot')
        .duration(140)
        .EUt(7)
    event.recipes.gtceu.alloy_smelter('pulsating_alloy_from_ingot')
        .itemInputs('minecraft:iron_ingot', 'minecraft:ender_pearl')
        .itemOutputs('gtceu:pulsating_alloy_ingot')
        .duration(140)
        .EUt(7)
    // Dark Steel
    event.remove({id:'enderio:alloy_smelting/dark_steel_ingot'})
    event.recipes.gtceu.alloy_smelter('dark_steel_from_dust')
        .itemInputs('#forge:dusts/iron', '#forge:obsidian')
        .itemOutputs('2x gtceu:dark_steel_ingot')
        .duration(240)
        .EUt(7)
    event.recipes.gtceu.alloy_smelter('dark_steel_from_ingot')
        .itemInputs('minecraft:iron_ingot', '#forge:obsidian')
        .itemOutputs('2x gtceu:dark_steel_ingot')
        .duration(240)
        .EUt(7)
    // Soularium
    event.remove({id:'enderio:alloy_smelting/soularium_ingot'})
    event.recipes.gtceu.alloy_smelter('soularium_from_dust')
        .itemInputs('#minecraft:soul_fire_base_blocks', '#forge:dusts/gold')
        .itemOutputs('gtceu:soularium_ingot')
        .duration(210)
        .EUt(24)
    event.recipes.gtceu.alloy_smelter('soularium_from_ingot')
        .itemInputs('#minecraft:soul_fire_base_blocks', 'minecraft:gold_ingot')
        .itemOutputs('gtceu:soularium_ingot')
        .duration(210)
        .EUt(24)
    // Conductive Alloy
    event.remove({id:'enderio:alloy_smelting/conductive_alloy_ingot'})
    event.recipes.gtceu.alloy_smelter('conductive_alloy_from_dust')
        .itemInputs('minecraft:iron_ingot', '#forge:dusts/redstone')
        .itemOutputs('gtceu:conductive_alloy_ingot')
        .duration(170)
        .EUt(7)
    event.recipes.gtceu.alloy_smelter('conductive_alloy_from_ingot')
        .itemInputs('minecraft:iron_ingot', '#forge:dusts/redstone')
        .itemOutputs('gtceu:conductive_alloy_ingot')
        .duration(170)
        .EUt(7)

    // Energetic Alloy
    event.remove({id:'enderio:alloy_smelting/energetic_alloy_ingot'})
    event.recipes.gtceu.mixer('energetic_alloy_dust')
        .itemInputs('2x #forge:dusts/gold', '#forge:dusts/redstone', '#forge:dusts/glowstone')
        .itemOutputs('4x gtceu:energetic_alloy_dust')
        .duration(264)
        .EUt(120)
        .circuit(3)
    // Vibrant Alloy
    event.remove({id:'enderio:alloy_smelting/vibrant_alloy_ingot'})
    event.recipes.gtceu.mixer('vibrant_alloy_dust')
        .itemInputs('gtceu:energetic_alloy_dust', '#forge:dusts/ender_pearl')
        .itemOutputs('2x gtceu:vibrant_alloy_dust')
        .duration(234)
        .EUt(120)
        .circuit(1)
    // End Steel
    event.remove({id:'enderio:alloy_smelting/end_steel_ingot'})
    event.recipes.gtceu.mixer('end_steel_dust')
        .itemInputs('#forge:dusts/dark_steel', '#forge:dusts/endstone', '#forge:dusts/vibrant_alloy')
        .itemOutputs('3x gtceu:end_steel_dust')
        .duration(216)
        .EUt(480)
        .circuit(1)
})