ServerEvents.recipes(event=>{

    event.remove({id: 'minecraft:netherite_ingot'})
    event.remove({id: 'nuclearcraft:rock_crusher/ancient_debris'})
    event.replaceOutput({}, 'minecraft:netherite_scrap', 'gtceu:crude_netherite_dust')
    
    // Copper Oxide
    event.recipes.gtceu.chemical_reactor("kubejs:copper_from_oxide")
        .itemInputs('gtceu:cupric_oxide_dust')
        .inputFluids('gtceu:hydrogen 2000')
        .itemOutputs('gtceu:copper_dust')
        .outputFluids('minecraft:water 1000')
        .duration(186)
        .EUt(96)
    // Molybdenum Disulfide
    event.recipes.gtceu.chemical_reactor("kubejs:molybdenum_disulfide")
        .itemInputs("8x gtceu:purified_molybdenum_ore", "8x gtceu:purified_pyrite_ore")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("8x gtceu:molybdenum_disulfide_dust", "8x gtceu:iron_dust")
        .outputFluids("gtceu:diluted_sulfuric_acid 1000")
        .duration(244)
        .EUt(480)
    // Silver Nitrate
    event.recipes.gtceu.chemical_reactor('kubejs:silver_nitrate')
        .itemInputs('#forge:dusts/silver')
        .inputFluids('gtceu:nitric_acid 1000')
        .itemOutputs('1x gtceu:silver_nitrate_dust')
        .outputFluids('minecraft:water 500')
        .duration(290)
        .EUt(30)
    // Silver Nitrate Solution
    event.recipes.gtceu.chemical_reactor('kubejs:silver_nitrate_solution')
        .itemInputs('gtceu:silver_nitrate_dust')
        .inputFluids('minecraft:water 1000')
        .outputFluids('gtceu:silver_nitrate_solution 1000')
        .duration(180)
        .EUt(24)
    // Silver Chloride
    event.recipes.gtceu.chemical_reactor('kubejs:silver_chloride')
        .itemInputs('4x gtceu:silver_phosphate_dust')
        .inputFluids('gtceu:hydrochloric_acid 3000')
        .itemOutputs('6x gtceu:silver_chloride_dust')
        .outputFluids('gtceu:phosphoric_acid 1000')
        .duration(338)
        .EUt(64)
    // Alumina
    event.recipes.gtceu.electrolyzer('kubejs:alumina')
        .itemInputs('2x gtceu:aluminium_hydroxide_dust')
        .itemOutputs('gtceu:alumina_dust')
        .outputFluids('minecraft:water 3000')
        .duration(144)
        .EUt(96)
    // Alumina Burning
    event.recipes.gtceu.electric_blast_furnace('kubejs:aluminium_from_hydroxide')
        .itemInputs('gtceu:alumina_dust', '3x #forge:dusts/carbon')
        .itemOutputs('2x gtceu:aluminium_ingot')
        .outputFluids('gtceu:carbon_monoxide 3000')
        .blastFurnaceTemp(2200)
        .duration(170)
        .EUt(480)

    // Netherite Processing
    event.recipes.gtceu.electric_blast_furnace('kubejs:poor_netherite')
        .itemInputs('3x gtceu:crude_netherite_dust', '4x minecraft:gold_ingot')
        .inputFluids('gtceu:hydrogen 2000')
        .itemOutputs('2x gtceu:small_netherite_dust')
        .outputFluids('gtceu:sulfuric_acid 1000')
        .blastFurnaceTemp(3300)
        .duration(780)
        .EUt(7680)
    event.recipes.gtceu.large_chemical_reactor('kubejs:acidic_netherite_solution')
        .circuit(17)    
        .itemInputs('6x gtceu:crude_netherite_dust', '4x gtceu:phosphorus_dust')
        .inputFluids('water 9000', 'gtceu:oxygen 10000', 'gtceu:sulfuric_acid 3000')
        .outputFluids('gtceu:acidic_netherite_solution 1000', 'gtceu:phosphoric_acid 2000', 'gtceu:diluted_sulfuric_acid 3000')
        .duration(444)
        .EUt(7680)
    event.recipes.gtceu.centrifuge('kubejs:enriched_netherite_dust')
        .inputFluids('gtceu:acidic_netherite_solution 1000')
        .itemOutputs('2x gtceu:small_enriched_netherite_dust')
        .chancedOutput('gtceu:small_enriched_netherite_dust', 1900, 600)
        .chancedOutput('gtceu:small_netherite_dust', 900, 400)
        .outputFluids('gtceu:phosphoric_acid 900')
        .duration(260)
        .EUt(240)
    event.recipes.gtceu.electric_blast_furnace('kubejs:netherite')
        .itemInputs('1x gtceu:enriched_netherite_dust',  '2x minecraft:gold_ingot')
        .itemOutputs('minecraft:netherite_ingot', '2x gtceu:small_netherite_dust')
        .blastFurnaceTemp(4900)
        .duration(894)
        .EUt(1920)

    // Chemical Netherite Line
    event.recipes.gtceu.chemical_reactor('kubejs:netherite_trisphosphate')
        .itemInputs('8x gtceu:purified_terraemantine_ore')
        .inputFluids('gtceu:sulfuric_acid 3000')
        .itemOutputs('8x gtceu:iron_ii_tungstate_trisphosphate_dust')
        .outputFluids('gtceu:diluted_sulfuric_acid 2000', 'gtceu:phosphoric_acid 1000')
        .duration(860)
        .EUt(480)
    event.recipes.gtceu.chemical_reactor('kubejs:netherite_bisphosphate')
        .itemInputs('gtceu:iron_ii_tungstate_trisphosphate_dust')
        .inputFluids('gtceu:silver_nitrate_solution 1500')
        .itemOutputs('gtceu:iron_ii_tungstate_bisphosphate_dust', '2x gtceu:silver_phosphate_dust')
        .outputFluids('gtceu:nitric_oxide 1000', 'gtceu:oxygen 2000')
        .duration(736)
        .EUt(480)
    event.recipes.gtceu.chemical_reactor('kubejs:netherite_phosphate')
        .itemInputs('gtceu:iron_ii_tungstate_bisphosphate_dust')
        .inputFluids('gtceu:iron_iii_chloride 1000')
        .itemOutputs('gtceu:iron_ii_tungstate_phosphate_dust', '2x gtceu:iron_iii_phosphate_dust')
        .outputFluids('gtceu:chlorine 3000')
        .duration(680)
        .EUt(480)
    event.recipes.gtceu.large_chemical_reactor('kubejs:netherite_dust')
        .circuit(13)
        .itemInputs('gtceu:iron_ii_tungstate_phosphate_dust', 'gtceu:aluminium_dust')
        .inputFluids('minecraft:water 2000', 'gtceu:hydrogen 7000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:crude_netherite_dust', 'gtceu:aluminium_hydroxide_dust')
        .outputFluids('gtceu:phosphoric_acid 1000')
        .duration(1120)
        .EUt(480)

})