
GTCEuStartupEvents.registry('gtceu:material', event =>{
    event.create("gabro")
        .dust()
        .color(0x2f332d).iconSet('dull')
        .components('2x iron', '1x silicon_dioxide', 'magnesium', '3x aluminium')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    
    event.create("vidium")
        .dust()
        .color(0xd89251).secondaryColor(0xc0c0c0).iconSet('dull')
        .element(GTElements.get("vidium"))

    event.create("viadium")
        .ingot(3).fluid()
        .color(0xe2bbfd).secondaryColor(0xb1b1b1).iconSet('dull')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD)
        .blastTemp(1250, 'low', 120, 380)
        .element(GTElements.get("viadium")) 
        .cableProperties(32, 2, 0, true)

    event.create("sapatanium")
        .ingot().fluid()
        .color(0xffdfba).iconSet('metallic')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD)
        .blastTemp(1650, 'low', 480, 710)
        .components('viadium', '2x chromium', 'manganese', 'gold')
        .cableProperties(128, 2, 0, true)
    
    event.create("fechantium")
        .ingot().fluid()
        .color(0xbae1ff).iconSet('metallic')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD)
        .blastTemp(2200, 'mid', 480, 960)
        .element(GTElements.get("fechantium"))
        .cableProperties(512, 2, 0, true)

    event.create("yottrium")
        .ingot().fluid()
        .color(0xbaffc9).iconSet('metallic')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD)
        .blastTemp(3300, 'mid', 1920, 705)
        .components('2x molybdenum', 'fechantium', '2x platinum','sulfur')
        .cableProperties(2048, 2, 0, true)

    event.create("denisium")
        .ingot().fluid()
        .color(0x1b85b8).secondaryColor(0xf7b685).iconSet('radioactive')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD)
        .blastTemp(4400, 'mid', 1920, 960)
        .components('2x uranium', 'yottrium', 'tungsten', '3x oxygen')
        .cableProperties(8192, 3, 0, true)
        
    event.create("avisium")
        .ingot().fluid()
        .color(0xf8ed62).iconSet('metallic')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD)
        .blastTemp(6300, 'high', 7680, 830)
        .element(GTElements.get("avisium"))
        .cableProperties(32768, 3, 0, true)
    
    event.create("travinite")
        .ore().addOreByproducts('magnetite', 'chromite', 'lithium')
        .color(0x666600)

})

GTCEuStartupEvents.materialModification(event =>{
    GTMaterials.get('gabro').setFormula('MgFe2Al3(SiO2)?')
    GTMaterials.get('yottrium').setFormula('Mo2FcPt2S')
    GTMaterials.get('denisium').setFormula('U2(Mo2FcPt2S)WO3')
    GTMaterials.get('travinite').setFormula('Li2(AvO3)O')
})