GTCEuStartupEvents.registry("gtceu:material", event=>{

    
    event.create("prosperity")
        .ingot()
        .ore(2, 1)
        .addOreByproducts('magnesium')
        .color(0xddfbfa).iconSet('metallic')
        .components("magnesium","2x aluminium", "silicon", "2x phosphate", "2x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("soulium")
        .dust()
        .color(0x5a3a2d)
        .components("copper", "3x hydrogen", "5x sulfur_dioxide")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        .ignoredTagPrefixes([TagPrefix.dustTiny, TagPrefix.dustSmall])
    event.create("soularium")
        .ingot()
        .color(0x7f6f55).secondaryColor(0x83715c).iconSet("dull")
        .components("soulium", "prosperity")
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create("inferium")
        .ingot().fluid()
        .ore(2, 3)
        .color(0x758d01).iconSet("metallic")
        .components("sodium", "aluminium", "silicon", "3x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.NO_SMELTING, GTMaterialFlags.GENERATE_GEAR)

    function mysticalIngot(i, p, clr){
        event.create(`${i}`)
            .ingot().fluid()
            .color(clr).iconSet("metallic")
            .components(`4x ${p}`)
            .flags(GTMaterialFlags.DISABLE_DECOMPOSITION, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.NO_SMELTING, GTMaterialFlags.GENERATE_GEAR)
            .ignoredTagPrefixes([TagPrefix.dustTiny, TagPrefix.dustSmall])
    }
    
    mysticalIngot('prudentium', 'inferium', 0x008623)
    mysticalIngot('tertium', 'prudentium', 0xb34b02)
    mysticalIngot('imperium', 'tertium', 0x0380da)
    mysticalIngot('supremium', 'imperium', 0xcb0000)
    mysticalIngot('insanium', 'supremium', 0x560484)

    event.create("awakened_supremium") 
        .ingot().fluid()
        .color(0xff3333).iconSet("radioactive")
        .element(GTElements.get('awakened_supremium'))
        .ignoredTagPrefixes([TagPrefix.dustTiny, TagPrefix.dustSmall])
        
        //.components("supremium")
        //.flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
 
    // Mystical Agriculture exclusive chemicals [WIP]
    /*
    event.create('air_elemental_solution')
        .fluid()
        .color()
        .components()
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('fire_elemental_solution')
        .fluid()
        .color()
        .components()
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('earth_elemental_solution')
        .fluid()
        .color()
        .components()
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('water_elemental_solution')
        .fluid()
        .color()
        .components()
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('earth_water_superelemental_solution')
        .fluid()
        .color()
        .components()
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('air_fire_superelemental_solution')
        .fluid()
        .color()
        .components()
        .flags()
    event.create('mystical_hyperconcetrate')
        .fluid()
        .color()
        .components()

    event.create('elemental_sludge')
        .dust()
        .color()
        .components("")
    */
    
})

GTCEuStartupEvents.materialModification(event =>{
    GTMaterials.get('prosperity').setFormula('Mg(AlPO4)2(SiO2)')
    GTMaterials.get('inferium').setFormula('NaAl(SiO2)')
    GTMaterials.get('prudentium').setFormula('(NaAl(AlPO4)2(SiO2)2)4')
    GTMaterials.get('tertium').setFormula('(NaAl(AlPO4)2(SiO2)2)16')
    GTMaterials.get('imperium').setFormula('(NaAl(AlPO4)2(SiO2)2)64')
    GTMaterials.get('supremium').setFormula('(NaAl(AlPO4)2(SiO2)2)256')
    // GTMaterials.get('awakened_supremium').setFormula('(NaAl(AlPO4)2(SiO2)2)256?')
    GTMaterials.get('insanium').setFormula('(NaAl(AlPO4)2(SiO2)2)1024')
    GTMaterials.get('soulium').setFormula('Cu(SO2)5H3?')
    GTMaterials.get('soularium').setFormula('CuMg(SO2)5(SiO3)H3?')
    })